# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 15:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='author_id',
            new_name='author',
        ),
    ]
