# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20170204_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
